// export type UserInfoType = {
//   ACT_TRAINING_END_DT?: string;
//   CARD_ID?: string;
//   CONTRACT_CNT?: string;
//   CONTRACT_END?: string;
//   CONTRACT_START?: string;
//   EXT1_AMT?: string;
//   EXT1_DT?: string;
//   EXT1_TXT?: string;
//   EXT2_AMT?: string;
//   EXT2_DT?: string;
//   EXT2_TXT?: string;
//   EXT3_TXT?: string;
//   EXT4_TXT?: string;
//   HUMAN_DIR_INDIR?: string;
//   MEDICAL_HIS?: string;
//   MEDICAL_TYPE?: string;
//   RACE_CD?: string;
//   SECT_CD?: string;
//   WORK_LINE?: string;
//   YEAR_AREA_CD?: string;
//   cannang?: string;
//   capbacdonvi?: string;
//   capbacnghiavu?: string;
//   capbacquansu?: string;
//   chieucao?: string;
//   cucnghiavuquansu?: string;
//   diachidkthuongtru?: string;
//   diachihientai?: string;
//   email?: string;
//   expi_dt?: string;
//   giotinh?: string;
//   grw_id?: string;
//   honnhan?: string;
//   hoten?: string;
//   luongphothong?: string;
//   luongvieclam?: string;
//   lydonghi?: string;
//   maamduong?: string;
//   mabacluong?: string;
//   cccd?: string;
//   mabophan?: string;
//   macapbac?: string;
//   machuctrach?: string;
//   machucvu?: string;
//   macongty?: string;
//   madonvi?: string;
//   makyniem?: string;
//   maloaituyendung?: string;
//   manguoidangky?: string;
//   manha?: string;
//   manv?: string;
//   maphongnoibo?: string;
//   maplquansu?: string;
//   maquandoi?: string;
//   matphai?: string;
//   matrai?: string;
//   matrangwweb?: string;
//   mavitri?: string;
//   maxephangcongviec?: string;
//   maxuong?: string;
//   mazipdkthuongtru?: string;
//   maziphientai?: string;
//   mumau?: string;
//   ngaydangky?: string;
//   ngayhethanthuviec?: string;
//   ngaykhuyenmai?: string;
//   ngaykhuyenmaicuoicung?: string;
//   ngaynghiviec?: string;
//   ngayroidi?: string;
//   ngaysinh?: string;
//   ngaytaituyendung?: string;
//   ngaythaydoi?: string;
//   ngaythaydoinhansu?: string;
//   ngayvaocongty?: string;
//   ngayvaolai?: string;
//   ngayvaolam?: string;
//   nhanluckthientruong?: string;
//   nhommau1?: string;
//   nhommau2?: string;
//   nhomquandoi?: string;
//   phanloaiquandoi?: string;
//   phanloaitructiepgiantiep?: string;
//   quanhevoinguoigioithieu?: string;
//   quequan?: string;
//   quocgia?: string;
//   sdt?: string;
//   sdtdidong?: string;
//   sdtkhancap?: string;
//   sothanglamviec?: string;
//   sothangnghiphep?: string;
//   tenbophan?: string;
//   tencongviecnguoigioithieu?: string;
//   teneng?: string;
//   tenkyniem?: string;
//   tennguoigioithieu?: string;
//   tentq?: string;
//   thoigianketthucquandoi?: string;
//   thoigianvaoquandoi?: string;
//   tinh?: string;
//   to_user?: string;
//   tongiao?: string;
//   trinhdochuyenmon?: string;
//   trinhdohocvan?: string;
//   vitringuoigioithieu?: string;
// };

export type UserInfoType = {
  ADDR?: string;
  APP_CD?: string;
  BIRT?: string;
  BIZ_AREA_CD?: string;
  BIZ_AREA_NM?: string;
  CAREER_MM?: number;
  COMP_CD?: string;
  CURR_ADDR?: string;
  DALT_TYPE?: string;
  DEPT_CD?: string;
  DEPT_NM?: string;
  DIR_INDIR?: string;
  DOMI?: string;
  EMAIL_ADDR?: string;
  EMP_NO?: string;
  ENG_NAME?: string;
  ENTR_DT?: string;
  EYESGT_LEFT?: number;
  EYESGT_RIGHT?: number;
  FUNC_CD?: string;
  GROUP_ENTR_DT?: string;
  HANJA_NAME?: string;
  HGT?: number;
  INTERNAL_CD?: string;
  INTERN_DT?: string;
  MEMO_CD?: string;
  MEMO_DT?: string;
  MINOR_NM?: string;
  NAME?: string;
  NAT_CD?: string;
  OCPT_TYPE?: string;
  ORDER_CHANGE_DT?: string;
  PAY_CD?: string;
  PAY_GRD1?: string;
  PAY_GRD2?: string;
  RESENT_PROMOTE_DT?: string;
  RES_NO?: string;
  RETIRE_RESN?: string;
  ROLL_PSTN?: string;
  SECT_CD?: string;
  SEX_CD?: string;
  SPOUSE?: string;
  TEL_NO?: string;
  WGT?: number;
  WK_AREA_CD?: string;
};
